- name: installing backend
  hosts: backend
  become: yes 
  tasks: 
    - name: desableing nodejs
      ansible.builtin.command: dnf module disable nodejs -y
        
    - name: enable node 20
      ansible.builtin.command: dnf module enable nodejs:20 -y

    - name: installing node 20
      ansible.builtin.dnf:
        name: nodejs 
        state: present 
    
    - name: useradd 
      ansible.builtin.user:
        name: expense
    
    - name: create app directory  # this will not impact the process
      ansible.builtin.file:
        path: /app 
        state: directory

    - name: Download the application
      ansible.builtin.get_url:
        url: https://expense-builds.s3.us-east-1.amazonaws.com/expense-backend-v2.zip
        dest: /tmp

    - name: unzipping 
      ansible.builtin.unarchive:
        src: /tmp
        dest: /tmp/backend.zip
        remote_src: yes

    - name: install npm dependencies 
      ansibile.builtin.shell: npm install
      args:
        chdir: /app

    - name: copy backend service 
      ansible.builtin.copy:
        src: backend.service
        dest: /etc/systemd/system/backend.service

    - name: daemon-reload
      ansible.builtin.systemd_service:
        daemon_reload: true  

    - name: start and enabling 
      ansible.builtin.service:
        name: backend
        enabled: yes
        state: started

    - name: install mysql 
      ansible.builtin.command: dnf install mysql -y
    
    - name: Load Schema
      ansible.builtin.command: mysql -h mysql.bigmatrix.in -uroot -pExpenseApp@1 < /app/schema/backend.sql

    - name: Restart backend 
      ansible.builtin.service:
        name: backend
        state: restarted


       


       